version: 0.0
os: windows
hooks:
  BeforeInstall:
    - location: \Get-DeploymentScripts.ps1
      timeout: 300
    - location: \Stop-ContentDelivery.ps1
      timeout: 300
  ApplicationStart:
    - location: \Deploy-WebPortalCD.ps1
      timeout: 300
    - location: \Cleanup-Artifacts.ps1
      timeout: 300
    - location: \Start-ContentDelivery.ps1
      timeout: 420
  ValidateService:
    - location: \Validate-ContentDelivery.ps1
      timeout: 300